on:
  release:
    types: [published]
  
  workflow_run:
    workflows: ["Scheduled Release"]
    types: [completed]
  
jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Trigger echo
        run: echo "A new release has been published."
