name: Scheduled Release

on:
  push

jobs:
  Release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v9.9.0
          release_name: v9.9.0
          draft: true
          prerelease: false

  Publish:
    needs: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    
      - id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - id: publish
        uses: eregon/publish-release@v1
        
        with:
          release_id: ${{ steps.fetch-latest-release.outputs.id }}
          GITHUB_TOKEN: ${{ secrets.actions }}
